<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="student-MS-7697" name="Command line test" tests="1" failures="1" timestamp="25 Apr 2016 13:12:52 GMT" time="0.048" errors="0">
  <testcase name="myTest" time="0.018" classname="com.itc7.kaprekar.AppTest">
    <failure type="java.lang.AssertionError" message="Incorrect Value! expected [8] but found [9]">
      <![CDATA[java.lang.AssertionError: Incorrect Value! expected [8] but found [9]
	at com.itc7.kaprekar.AppTest.myTest(AppTest.java:14)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:109)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- myTest -->
</testsuite> <!-- Command line test -->
